---
- name: Deploy Docker Container
  hosts: all
  gather_facts: true
  tasks:

    - name: Switch to logs folder
      shell: "cd /logs"
    
    - name: Create calculator.log file
      shell: "touch calculator.log"

    - name: ensure file exists
      copy:
        content: ""
        dest: /logs/calculator.log
        force: false
      ignore_errors: true

    - name: Pull docker container from docker hub
      shell: "docker pull rohitraman/calculator-project"
    
    - name: Run docker container on system
      shell: "docker run -v /logs/calculator.log:/calculator.log -it -d --name calculator rohitraman/calculator-project" 