---
- name: Deploy Docker Container
  hosts: all
  gather_facts: true
  tasks:
  
    - name: Pull docker container from docker hub
      shell: "docker pull rohitraman/calculator-project"
    
    - name: Run docker container on system
      shell: "docker run -it -d --name calculator rohitraman/calculator-project" 